#!/bin/sh

# set internal field separator (IFS) to "\n" for shell commands
set ifs "\n"
# set '-eu' options for shell commands
set shellopts '-eu'

map <enter> shell
map D delete
map <backspace2> set hidden!
map <backspace> set hidden!

cmd open ${{
case $(file --mime-type $f -b) in
    text/*) $EDITOR $fx;;
    image/*) feh $fx;;
    video/*) mpv --really-quiet --no-terminal --force-window $fx &;;
    application/pdf) zathura --fork $fx;;
    *) $EDITOR $fx;;
esac
}}

cmd delete ${{
set -f
printf "$fx\n"
printf "delete? [y/n] "
read ans
[ $ans = "y" ] && rm -rf $fx
}}

