#! /bin/sh
sxhkd &
picom &
unclutter &
feh --bg-scale ~/Pictures/Wallpapers/otachan.png &

killall -q polybar
polybar bar &
bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1-1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI1 -d Z ZZ ZZZ

bspc config active_border_color     '#dddddd'
bspc config focused_border_color    '#dddddd'

bspc config border_width            2
bspc config window_gap              30
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config -m eDP1 top_padding     20
bspc config -m eDP-1-1 top_padding  20
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule --add Zathura             state=tiled
