#!/bin/sh

bspc monitor -d 1 2 3 4 5 

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle	true

bspc rule -a Zathura state=tiled
