#! /bin/sh
sxhkd &
polybar bar &
compton -f &
unclutter &
feh --bg-scale ~/Pictures/Wallpapers/10.png &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		0
bspc config window_gap			10

bspc config split_ratio			0.50
bspc config borderless_monocle	true
bspc config gapless_monocle		false

bspc rule --add Zathura			state=tiled
