import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Inconsolata Nerd Font Mono"

[scrolling]
multiplier = 3

[window.padding]
x = 4
y = 4
