[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "Inconsolata Nerd Font Mono"

[scrolling]
multiplier = 3

[window.padding]
x = 2
y = 2

[general]
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

